version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://avnadmin:AVNS_m9oyag8y4lA9tCzfy0n@sellscale-challenge-db-sellscale-challenge.d.aivencloud.com:21594/sellscale-db?sslmode=require
      - ALPHA_VANTAGE_API_KEY=5HG2WQ7ISQIJXUK3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
